version: "2"
volumes:
  influxdb-data:
  grafana-xxl-data:
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    volumes:
      - influxdb-data:/var/lib/influxdb
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "8083:8083"
      - "8086:8086"
    environment:
      - INFLUXDB_ADMIN_ENABLED=true
    restart: always
  grafana-xxl:
    image: monitoringartist/grafana-xxl:latest
    container_name: grafana-xxl
    volumes:
      - grafana-xxl-data:/var/lib/grafana
    ports:
      - "3100:3000"
    links:
      - influxdb
    restart: always
  glances:
    image: nicolargo/glances
    container_name: glances
    volumes:
      - ./glances.conf:/glances/conf/glances.conf 
      - /var/run/docker.sock:/var/run/docker.sock:ro 
    links:
      - influxdb
    pid: "host"
    # interactive mode
    stdin_open: true
    tty: true
    # web server mode
    #restart: always
    #ports:
    #  - "61208-61209:61208-61209"
    #environment:
    #  - GLANCES_OPT=-w
    # influxdb export mode
    environment:
      - GLANCES_OPT=--export-influxdb -t 10 -d -q
    #restart: no
  telegraf:
    image: telegraf
    container_name: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro 
    links:
      - influxdb


