version: '2'
volumes:
  atlassian-jira-db-data:
  atlassian-jira-software-db-data:
services:
  atlassian-jira-mta:
    image: relaxart/docker-sendmail
    container_name: atlassian-jira-mta
    ports:
      - 25

  atlassian-jira-db:
    image: postgres:latest
    container_name: atlassian-jira-db
    ports:
      - 15432:5432
    volumes:
      - atlassian-jira-db-data:/data
    environment:
      - PGDATA=/data
      - POSTGRES_DB=jira
      - POSTGRES_USER=jirauser
      - POSTGRES_PASSWORD=jirapass

  atlassian-jira:
    image: cptactionhank/atlassian-jira:latest
    container_name: atlassian-jira
    links:
      - atlassian-jira-mta
      - atlassian-jira-db
    ports:
      - 18080:8080

  atlassian-jira-software-db:
    image: postgres:latest
    container_name: atlassian-jira-software-db
    ports:
      - 15433:5432
    volumes:
      - atlassian-jira-software-db-data:/data
    environment:
      - PGDATA=/data
      - POSTGRES_DB=jira
      - POSTGRES_USER=jirauser
      - POSTGRES_PASSWORD=jirapass

  atlassian-jira-software:
    image: cptactionhank/atlassian-jira-software:latest
    container_name: atlassian-jira-software
    links:
      - atlassian-jira-mta
      - atlassian-jira-software-db
    ports:
      - 18081:8080


